ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.PrintName = "Cannon"
ENT.Author	= "Matthew"
ENT.Contact	= ""
ENT.Purpose	= ""
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.Category = "The Middle Ages" 