ENT.Base 			= "base_anim"
ENT.Type 			= "anim"
ENT.Category 		= "Medieval Roleplay"
ENT.PrintName		= "Fishing Hook"
ENT.Author			= "G3X n' ReaperSWE"
ENT.Contact			= ""
ENT.Purpose			= "To attach to the Fishing Rod."
ENT.Instructions	= ""
ENT.Spawnable		= false
ENT.AdminSpawnable	= true