ENT.Base			= "base_anim"
ENT.Type 			= "anim"
ENT.Category 		= "Medieval Roleplay"
ENT.PrintName		= "Fishing Bait"
ENT.Author			= "G3X n' ReaperSWE"
ENT.Contact			= ""
ENT.Purpose			= "Used as bait to catch fish."
ENT.Instructions	= ""
ENT.Spawnable		= true
ENT.AdminSpawnable	= true