ENT.Base			= "base_anim"
ENT.Type			= "anim"
ENT.Category 		= "Medieval Roleplay"
ENT.PrintName		= "Fishing Rod"
ENT.Author			= "G3X n' ReaperSWE"
ENT.Contact			= ""
ENT.Purpose			= "To fish with."
ENT.Instructions	= ""
ENT.Spawnable		= false
ENT.AdminSpawnable	= true